baseURL: https://example.com
languageCode: en-us
defaultContentLanguage: en
title: DicePunk
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  # footer: Victor "Stolen" Furtado - 2022
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  defaultDarkTheme: true
  moveFooterToHeader: true
  # navTitleText: Cupper Theme
  logoAlt: DicePunk

menu:
  nav:
    - name: Introdução
      url: /
      weight: 1
    - name: Regras Básicas
      url: /basic_rules
      weight: 2
    - name: Blog
      url: /post/
      weight: 97 
    - name: Tags
      url: /tags/
      weight: 98
    - name: RSS
      url: /index.xml
      weight: 99

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
